name: mountainsort_examples

channels:
 - conda-forge
 - flatiron

dependencies:
 - python=3.6
 - matplotlib
 - mountainlab=0.14.4
 - kbucket=0.10.2
 - mountainlab_pytools=0.6.8
 - spikeforestwidgets=0.1.4
